### PR TITLE
Added `sendphoto` command and updated README.md

### LINKED ISSUE #23: "sendPhoto" command to send a photo by url
https://core.telegram.org/bots/api#sendphoto

### PR DESCRIPTION
**Pull request by willumz**
Command `sendphoto` added which sends a photo from a URL to a channel.
README.md updated to include `sendgif` and `sendphoto` commands, along
with examples added to `src/examples`.

Closes #23

### CODE REVIEW

**Comment by woltsu** [comment]
I'll get back to these tomorrow, thanks for the contributions @Willumz

**Comment by woltsu** [comment]
In send photo command on line 26 you've written `photo=$<<parameters.image-url>>`. The symbol `$` isn't needed here. Could you remove it?

**Comment by willumz** [comment]
My bad, that should be fixed now.

**Comment by woltsu** [comment]
Thanks @Willumz!

**Pull request merged**
