### PR TITLE
Feature: Send stickers by url or file_id

### PR DESCRIPTION
**Pull request by AMoldskred**

### CODE REVIEW

**Comment by woltsu** [comment]
In the sendSticker command on line 25 you've written `$<<parameters.telegram-sticker>>`. You don't need the `$` symbol there, because it isn't an environmental variable. I think otherwise it looks good, apart from some indentation. Could you remove the `$` symbol?

**Comment by woltsu** [comment]
I also think that the default url should be an empty string, and if none is given then the user should be warned.

**Comment by AMoldskred** [comment]
@woltsu Fixed what you asked for :). Thanks for the feedback!

**Comment by woltsu** [comment]
I changed the base branch to Alpha instead of master. Could you solve the conflicts? I also think that it would be nicer if the parameter `telegram-sticker` would be called `telegram-sticker-url` instead. Thanks!

**Comment by AMoldskred** [comment]
Fixed

**Comment by woltsu** [comment]
Thanks @andreas0607!

**Pull request merged**
